### ISSUE TITLE
no SNP found

### ISSUE THREAD

**Issue by rchikhi** [tseemann/ekidna#14]
For the record, I ran Ekidna on a bunch of already-assembled bacterial genomes, and the output was:

```
[..]
[ekidna] Deriving core SNP alignment: ekidna.aln
[ekidna] Running: (snp-sites -c -o ekidna.aln ekidna.full.aln) 2>&1 | tee -a '/..]/ekidna.log'
Warning: No SNPs were detected so there is nothing to output.
[..]
```

With the following output files:

```
$ ll output/
total 13643341
drwxr-sr-x 2 rchikhi cifs- 120 Jul  3 10:15 .
drwxr-sr-x 3 rchikhi cifs- 45 Jul  2 12:21 ..
-rw-r--r-- 1 rchikhi cifs- 3179826 Jul  3 03:09 ekidna.fna
-rw-r--r-- 1 rchikhi cifs- 12375917205 Jul  3 07:52 ekidna.full.aln
-rw-r--r-- 1 rchikhi cifs- 853 Jul  3 03:09 ekidna.genome
-rw-r--r-- 1 rchikhi cifs- 8058765 Jul  3 08:20 ekidna.log
```

**Comment by tseemann** [comment]
They need to be similar genomes, so that minimap2 can align blocks. Also, it only finds CORE snps, so if you have 1 genome different to the other N-1 genomes, you will get no output.  Could that be the case here?

**Comment by rchikhi** [comment]
"if you have 1 genome different to the other N-1 genomes"

that's very likely the case, yes. Thanks!
